name: Android CI

on:
  push:
    branches: [ "master" ]
    tags: [ "v*" ] # 当 tag 以 "v" 开头时触发
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew :app:assembleRelease

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY_BASE64 }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Rename Signed APK
        run: mv ${{ steps.sign_app.outputs.signedReleaseFile }} app/build/outputs/apk/release/RedefineNCM_${{ github.ref_name }}.apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RedefineNCM_${{ github.ref_name }}
          path: app/build/outputs/apk/release/RedefineNCM_${{ github.ref_name }}.apk

      - name: Upload APK to Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          APK_FILE="app/build/outputs/apk/release/RedefineNCM_${{ github.ref_name }}.apk"
          echo "Uploading $APK_FILE to Telegram..."
          curl -F chat_id=$TELEGRAM_CHAT_ID \
               -F document=@"$APK_FILE" \
               -F caption="✅ RedefineNCM ${{ github.ref_name }} New push！" \
               https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendDocument

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v') # Only on tag pushed
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download APK from Artifacts
        uses: actions/download-artifact@v4
        with:
          name: RedefineNCM_${{ github.ref_name }}
          path: app/build/outputs/apk/release/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/release/RedefineNCM_${{ github.ref_name }}.apk
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          body: "Auto build Release Version! 🎉"
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
