name: Android CI

on:
  push:
    branches: [ "master" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Count commits since last tag
        id: commitcount
        run: |
          git fetch --tags
          latest_tag=$(git describe --tags --abbrev=0)
          count=$(git rev-list --count ${latest_tag}..HEAD)
          echo "count=$count" >> $GITHUB_OUTPUT

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew :app:assembleRelease

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY_BASE64 }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Rename Signed APK
        run: mv ${{ steps.sign_app.outputs.signedReleaseFile }} app/build/outputs/apk/release/RedefineNCM_${{ github.ref_name }}.apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RedefineNCM_${{ github.ref_name }}
          path: app/build/outputs/apk/release/RedefineNCM_${{ github.ref_name }}.apk

      - name: Get commit info
        id: gitinfo
        run: |
          echo "commit_msg=$(git log -1 --pretty=%s)" >> "$GITHUB_OUTPUT"
          echo "commit_sha=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Upload APK to Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          APK_FILE="app/build/outputs/apk/release/RedefineNCM_${{ github.ref_name }}.apk"
          echo "Uploading $APK_FILE to Telegram..."

          CAPTION=$(cat <<EOF
          ✅ *RedefineNCM* \`${{ github.ref_name }}\`
          📝 _${{ steps.gitinfo.outputs.commit_msg }}_ \`[${{ steps.gitinfo.outputs.commit_sha }}]\`
          📦 *${{ steps.commitcount.outputs.count }}* commits since last tag
          EOF
          )

          curl -F chat_id="$TELEGRAM_CHAT_ID" \
               -F document=@"$APK_FILE" \
               -F caption="$CAPTION" \
               -F parse_mode="Markdown" \
               https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendDocument

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v') # Only on tag pushed
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Get commit messages since last tag
        id: commits
        run: |
          git fetch --tags
          tags=($(git tag --sort=-creatordate))
          current_tag=${tags[0]}
          previous_tag=${tags[1]}

          echo "Previous tag: $previous_tag"
          echo "Current tag: $current_tag"

          commit_log=$(git log --oneline ${previous_tag}..${current_tag})
          commit_count=$(git rev-list --count ${previous_tag}..${current_tag})

          echo "log<<EOF" >> $GITHUB_OUTPUT
          echo "$commit_log" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "count=$commit_count" >> $GITHUB_OUTPUT

      - name: Download APK from Artifacts
        uses: actions/download-artifact@v4
        with:
          name: RedefineNCM_${{ github.ref_name }}
          path: app/build/outputs/apk/release/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/release/RedefineNCM_${{ github.ref_name }}.apk
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          body: |
            🎉 **Auto build new version!**
            
            📦 **${{ steps.commits.outputs.count }} commits since last release**
            ```
            ${{ steps.commits.outputs.log }}
            ```
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
